apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - image: argoproj/rollouts-demo:green
        name: simple
        ports:
        - containerPort: 8080
